### ISSUE TITLE
Support multiple tags per topic

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-message-service#65]
As of now we only support single tag per topic which is somewhat restrictive. We need to update the topic model so that it allows multiple tags per topic.

fyi @gondzo

**Comment by gondzo** [comment]
@vikasrohit with this change we have param 'tags' instead of 'tag' that we had before 
https://github.com/appirio-tech/tc-message-service/blob/502a0edce213c24d4e86c4a15d3c4006d26d6f74/app/routes/topics/create.js#L40

That means we would have to update all calls to the api (I guess it's only Connect?) or we should revert and use 'tag' name as before.

**Comment by vikasrohit** [comment]
I would prefer keeping it `tag` for now. So that we don't have to manage its callers.

**Comment by gondzo** [comment]
@vikasrohit done
One issue with the dev database though - the original change added a migration to create a column `tags` and remove column `tag` without migrating the data, so essentially we have lost the value of tag column in dev database. 
I've fixed the migration, so can you manually run `npm run migrate:undo` and then `npm run migrate` in dev env so we can have the db in sync.
Also, please review the migration, we don't want to do the same mistake on prod 😬 
https://github.com/appirio-tech/tc-message-service/blob/feature/elastic_search_indexing_6.3/migrations/20180604100352-tags-support.js

**Comment by gondzo** [comment]
I'm not sure if migrations are automatically run when deploying. if not, then just running `npm run migrate' should be fine

**Comment by vikasrohit** [comment]
We are not running database migrations with build. It it manual, just to avoid such cases. 😬 I think we are good with the data.

**Comment by gondzo** [comment]
awesome. in that case, just run the migration on dev so we can test everything in dev.

**Comment by vikasrohit** [comment]
@gondzo I can still see the reference to the `tags` in migration script. Am I looking at wrong place? https://github.com/appirio-tech/tc-message-service/blob/feature/elastic_search_indexing_6.3/migrations/20180604100352-tags-support.js

**Comment by gondzo** [comment]
Tags is a field in DB (string array). Tag is a field in API json request/response (comma separated string)

**Comment by vikasrohit** [comment]
Ohk. And we are not loosing the old tag now with latest migration script, right? I mean we are copying the old tag field value in new tags field.

**Comment by gondzo** [comment]
Right, tag column is copied to the new tags column
https://github.com/appirio-tech/tc-message-service/blob/dad71facb51204db8fe39ae6f22a5ac378bcaa82/migrations/20180604100352-tags-support.js#L14
